name: chasski
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  pocketbase: ^0.18.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  cached_network_image: ^3.3.1
  connectivity_plus: ^5.0.2 #Gestionar conectividad de internet
  http: ^1.2.1
  sqflite: ^2.3.3  #para SQL LITE Base de datos local, trabaja con path provider
  path: ^1.8.3 #Para SQL LITE Nos sirve para unir elementos. trabaja con SQL lite 
  path_provider: ^2.1.2 #para SQL LITE encontrar ubicaciones de uso común en el sistema de archivos
  pdf: ^3.11.0 #exportar pdf
  excel: ^4.0.3  #exportar excel
  open_filex: ^4.3.4  #abrir archivo y requiere de path provider
  flutter_tts: ^3.8.5 #de text a voz 
  speech_to_text: ^6.5.1
  image_picker: ^1.1.2
  qr_flutter: ^4.1.0
  flutter_barcode_scanner: ^2.0.0
  widget_circular_animator: ^1.0.0 #ANimacion QR Datils Personal
  fade_out_particle: ^1.2.1 #Animacion Qr LEctor 
  simple_ripple_animation: ^0.0.9 #Animacion Qr Insta Qr Scanner
  quickalert: ^1.0.2 #ALerta SHow Dialog 
  delayed_display: ^2.0.0 #EFECTO opacity al iniciar la pantalla
  # draggable_home: ^1.0.5 #Efecto Expandible de el appber
  syncfusion_flutter_charts: ^24.2.9  #Graficos DASHBORAD  
  vibration: ^1.9.0 #vibrar al snacear un codgio qr
  audioplayers: ^6.0.0 #reproducir tonpo al scanear QR
  elegant_notification: ^2.2.0
  # numeric_keyboard: ^1.1.0
  flutter_keyboard: ^2.0.3
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2
  flutter_expanded_tile: ^0.4.0
  timelines: ^0.1.0 #LINEA DE TIEMPO 
  timezone: ^0.9.3 #HORARIO LOCAL 
  file_picker: ^8.0.0 #SUbir Archivos
  flutter_pdfview: ^1.3.2 #Previsualizar PDF antes de subirlo. 
  signature: ^5.5.0 #Poder Firma , efecto pizarra 
  # local_auth: ^2.1.8
  screenshot: ^3.0.0 
  image_gallery_saver: ^2.0.3 #Acceso a Galleria 
  permission_handler: ^11.3.1 #PErmisos de Galleria.SOLO EN ANDROID
  banner_carousel: ^1.2.1
  url_launcher: ^6.3.0
  cupertino_stepper: ^0.2.1 #Menu desplegable en orden. Steeper 
  # webview_flutter: ^4.8.0
  # country_code_picker: ^3.0.0 #CPOUNTRY RUNNER 
  #FIREBASE 
  # firebase_core: ^3.1.0 
  # cloud_firestore: ^5.0.1
  # firebase_messaging: ^15.0.2 #Requiere Pago APPLE DEVELOPER $99
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
 
flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/img/icon_app.png"
  flutter_lints: ^4.0.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
      - assets/img/
      - assets/loties/
      - assets/svg/
      - assets/song/
  # example:
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 300
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 600
 